name: wdb_practise

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-comparison:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install "wandb[workspaces]" ghapi

      - name: Generate comparison report
        run: |
          python ./client/compare_runs.py
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          WANDB_ENTITY: ${{ secrets.WANDB_ENTITY }}
          WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
          BASELINE_TAG: baseline
          RUN_ID: ${{ github.event.pull_request.head.sha }} # Adjust if you need to pass different value for run_id

      - name: Output comparison report URL
        run: |
          echo "Comparison report URL: ${{ steps.generate-report.outputs.REPORT_URL }}"
